### ISSUE TITLE
[feature request] don't send email to event participants if the event gets deleted

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/proton-calendar#21]
There might be past events in a calendar or created by mistake. Currently the system automatically sends the email about event deleting to the participants which in my opinion in many cases doesn't make sense and is annoying in general.

Suggested change:
- Keep the feature but make it opt-in (so it's becoming configurable in the settings and disabled by default),
- Add respective checkbox to the event deleting modal so one-time default calendar setting overriding is possible.

**Comment by econdepe** [comment]
Hi Vladimir,

Thanks for the suggestion. I don't think it's a good idea to not send a cancellation email for an invite that you delete because you created it by mistake, as the attendees would have received an invitation email and they would have no way to know that it was a mistake and that the event is not happening. Instead, for the case of a past event, it does make sense to make optional the sending of the cancellation email.

It wouldn't be too hard to modify the "delete event" confirmation modal, adding a checkbox in the case the event is in the past that the user would have to tick if they want to send a cancellation email.

It's in the plans to create some settings to control when to send an email and when not -- for instance sending invites/updates for past events is also not very useful, and for updates to internal invites (Proton organizer, Proton attendees) there's no need of notifying by email to get the event change in the calendar. However this requires some back-end changes and cannot be handled client-side alone.

**Comment by vladimiry** [comment]
The cases I listed was just an example, there are of course more cases. The most annoying case is related to the past events, when I want to silently remove from my calendar the past events (currently the attendees get spammed for no reason).

> However this requires some back-end changes and cannot be handled client-side alone.

Sure but I don't know other way how to place the issue which will be noticed by @protonmail engineers.

**Comment by econdepe** [comment]
There's definitely room for improvement for this issue and plans to work on it.

We are gonna publish in this repo soon some guidelines to streamline the process of making feature requests and bug reports. In the meantime, the preferred way of asking for features is via [uservoice](https://protonmail.uservoice.com/forums/932842-proton-calendar), which do reach the dev team ;)

**Comment by vladimiry** [comment]
I treat sending emails related to past events as a bug but uservoice looks more like a voting system than a place to post a bug reports.

**Comment by econdepe** [comment]
IMO it's arguable whether that's a bug or a feature, but at any rate the process for reporting bugs will also be streamlined. At the moment the best way is to use the "Report problem" button. Those also reach the dev team ;)

**Comment by vladimiry** [comment]
Ok. I made the point. Hope it's placed somewhere in internal bug tracker (Jira stuff I guess). Also hope one day @protonmail moves to the "open-source first" development model for the open projects.
